# Generated by Django 3.0.3 on 2020-02-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='crop',
            field=models.CharField(default='Wheat', max_length=30),
        ),
    ]
